import { HARMOST_SCHEMA_VERSION } from './compat.js';
import { Lines, inlineList, quote } from './yaml.js';

/**
 * Turn a Next dynamic route into a Harmost path glob.
 *
 *   /products/[slug]      -> /products/*
 *   /blog/[...slug]       -> /blog/**            (not /blog itself, as in Next)
 *   /shop/[[...slug]]     -> {/shop,/shop/**}    (Next matches /shop too)
 *
 * Harmost compiles globs without `literal_separator`, so `*` crosses `/`:
 * `/products/*` also matches `/products/a/b`. That is measured, not assumed,
 * and it is why generated dynamic routes default to a private class — an
 * over-matching pattern with a private policy costs a little reuse, while an
 * over-matching pattern with a public one is a correctness problem.
 */
export function toGlob(page) {
  const optional = page.match(/^(.*)\/\[\[\.\.\.[^\]]+\]\]$/);
  if (optional) {
    const parent = optional[1] || '';
    return `{${parent || '/'},${parent}/**}`;
  }
  return page.replace(/\/\[\.\.\.[^\]]+\]/g, '/**').replace(/\[[^\]]+\]/g, '*');
}

/** A stable, readable, unique route id derived from a page path. */
export function routeId(page, taken) {
  const base =
    page
      .replace(/\[\[?\.{0,3}([^\]]*?)\]?\]/g, '$1')
      .replace(/[^a-zA-Z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .toLowerCase() || 'root';
  let id = base;
  let n = 2;
  while (taken.has(id)) id = `${base}-${n++}`;
  taken.add(id);
  return id;
}

/** Is this app-router route a Route Handler rather than a page? */
function isRouteHandler(appPaths, page) {
  return Object.entries(appPaths).some(([file, route]) => route === page && file.endsWith('/route'));
}

/**
 * Generate a Harmost configuration from a Next build.
 *
 * The governing rule is that **anything the build does not prove is shareable
 * is private**. A prerendered route is proof: Next generated one response for
 * everybody, so it can be shared with everybody. A dynamically rendered route
 * is not proof of anything — it may read cookies, headers or a session — so it
 * is generated as `private_dynamic` with a comment saying how to opt in.
 *
 * That direction is deliberate. A generator that guessed `public_ssr` would be
 * one bad guess away from serving one user's page to another, and it would do
 * it silently, in a file nobody reads closely because a tool wrote it.
 */
export function generateConfig(build, options = {}) {
  const {
    includeDeployment = true,
    defaultTtl = '1s',
    staleIfError = '1m',
    upstreams = [],
    concurrency = 200,
    lowPriorityPercent = 30,
  } = options;
  const base = build.basePath || '';
  const p = (suffix) => `${base}${suffix}`;
  const taken = new Set();
  const out = new Lines();

  out.comment(
    'Generated by @harmost/next from a Next.js build. Do not edit by hand:\n' +
      'regenerate after each build so `deployment.id` and the route list stay in\n' +
      'step with what is actually deployed.\n' +
      '\n' +
      `Next build id:      ${build.buildId}\n` +
      `routes-manifest:    v${build.manifestVersions.routes}\n` +
      `prerender-manifest: ${build.manifestVersions.prerender === null ? 'absent' : 'v' + build.manifestVersions.prerender}\n` +
      '\n' +
      'Every route the build does not PROVE is shareable is generated as\n' +
      '`private_dynamic`. Prerendered routes are proof — Next produced one\n' +
      'response for everybody. Dynamically rendered routes are not, because they\n' +
      'may read cookies or headers, so opting one into `public_ssr` is a decision\n' +
      'only you can make.',
  );
  out.raw(`version: ${HARMOST_SCHEMA_VERSION}`);

  if (includeDeployment) {
    out.raw();
    out.comment(
      'The build id. It is part of every cache key, so a new build is never\n' +
        "served the previous build's entries — and a SIGHUP that changes it\n" +
        'purges them.',
    );
    out.raw('deployment:');
    out.raw(`  id: ${quote(build.buildId)}`);
  }

  if (upstreams.length > 0) {
    out.raw();
    out.comment(
      'Where the Next.js servers are. `concurrency.max` is the one number here\n' +
        'that has to come from your own measurement: it is the ceiling on how\n' +
        'much work the origin is asked to do at once, and the right value is a\n' +
        'property of your renders and your hardware, not of your framework.\n' +
        '\n' +
        '`priorities.low` reserves the rest of that ceiling for page renders, so\n' +
        'a burst of image transforms cannot starve them.',
    );
    out.raw('origin:');
    out.raw(`  upstreams: ${inlineList(upstreams)}`);
    out.raw('  concurrency:');
    out.raw(`    max: ${concurrency}`);
    out.raw('  priorities:');
    out.raw(`    low: ${lowPriorityPercent}`);
  }

  out.raw();
  out.raw('routes:');

  out.raw();
  out.comment('Fingerprinted build output. Immutable, and serving it is not rendering.', 2);
  out.raw(`  - id: ${quote(routeId('next-static', taken))}`);
  out.raw(`    match: ${quote(p('/_next/static/**'))}`);
  out.raw('    class: static');

  out.raw();
  out.comment(
    'The image optimiser. `vary: [Accept]` is load-bearing: Next negotiates the\n' +
      'output format on Accept and answers `Vary: Accept`, so without it in the\n' +
      'key Harmost refuses to store anything and this route gets a 0% hit rate.\n' +
      '`priority: low` and `weight` keep image transforms — several hundred\n' +
      'milliseconds of origin CPU each — from starving page renders.',
    2,
  );
  out.raw(`  - id: ${quote(routeId('next-image', taken))}`);
  out.raw(`    match: ${quote(p('/_next/image'))}`);
  out.raw('    class: public_dynamic');
  out.raw('    priority: low');
  out.raw('    weight: 4');
  out.raw('    cache:');
  out.raw('      ttl:');
  out.raw('        max: 1h');
  out.raw('      query:');
  out.raw('        mode: include');
  out.raw(`        keys: ${inlineList(['url', 'w', 'q'])}`);
  out.raw('      vary:');
  out.raw(`        headers: ${inlineList(['Accept'])}`);

  const prerendered = Object.entries(build.prerendered)
    .filter(([route]) => !route.startsWith('/_'))
    .sort(([a], [b]) => a.localeCompare(b));
  if (prerendered.length > 0) {
    out.raw();
    out.comment(
      'Prerendered routes. Next generated one response for everybody, which is\n' +
        'what makes `override_origin` correct here rather than a guess: the build\n' +
        'is the evidence.',
      2,
    );
    for (const [route, entry] of prerendered) {
      const revalidate = entry.initialRevalidateSeconds;
      const ttl = typeof revalidate === 'number' && revalidate > 0 ? `${revalidate}s` : '1h';
      out.raw(`  - id: ${quote(routeId(`page${route}`, taken))}`);
      out.raw(`    match: ${quote(p(route))}`);
      out.raw('    class: public_ssr');
      out.raw('    cache:');
      out.raw('      override_origin: true');
      out.raw('      ttl:');
      out.raw(`        max: ${ttl}`);
      out.raw(`      stale_if_error: ${staleIfError}`);
      out.raw('    coalesce:');
      out.raw('      enabled: true');
    }
  }

  const handlers = [...new Set(Object.values(build.appPaths))]
    .filter((route) => isRouteHandler(build.appPaths, route))
    .sort();
  if (handlers.length > 0) {
    out.raw();
    out.comment(
      'App Router route handlers. Generated private: a handler is code, and\n' +
        'nothing in the build says what it reads.',
      2,
    );
    for (const route of handlers) {
      out.raw(`  - id: ${quote(routeId(`api${route}`, taken))}`);
      out.raw(`    match: ${quote(p(toGlob(route)))}`);
      out.raw('    class: private_dynamic');
      out.raw('    cache:');
      out.raw('      enabled: false');
    }
  }

  const prerenderedSet = new Set(prerendered.map(([route]) => route));
  const handlerSet = new Set(handlers);
  const pages = [...new Set([...build.staticRoutes, ...build.dynamicRoutes].map((r) => r.page))]
    .filter(
      (page) => page && !page.startsWith('/_') && !prerenderedSet.has(page) && !handlerSet.has(page),
    )
    .sort();
  if (pages.length > 0) {
    out.raw();
    out.comment(
      'Dynamically rendered pages. Private by default — the build does not say\n' +
        'whether these read cookies or headers. If one is genuinely the same for\n' +
        'every visitor, change it to:\n' +
        '\n' +
        '    class: public_ssr\n' +
        '    cache:\n' +
        '      override_origin: true\n' +
        `      ttl: { max: ${defaultTtl} }\n` +
        '    coalesce: { enabled: true }\n' +
        '\n' +
        'A dynamically rendered Next route answers `no-store`, so the override is\n' +
        'required or nothing here is ever cached or collapsed.',
      2,
    );
    for (const page of pages) {
      out.raw(`  - id: ${quote(routeId(`page${page}`, taken))}`);
      out.raw(`    match: ${quote(p(toGlob(page)))}`);
      out.raw('    class: private_dynamic');
      out.raw('    cache:');
      out.raw('      enabled: false');
    }
  }

  out.raw();
  out.comment(
    'Anything not named above. Private, so a route added to the app after this\n' +
      'file was generated is safe rather than shared.',
    2,
  );
  out.raw(`  - id: ${quote(routeId('default', taken))}`);
  out.raw(`    match: ${quote(p('/**'))}`);
  out.raw('    class: private_dynamic');
  out.raw('    cache:');
  out.raw('      enabled: false');

  return out.toString();
}
